version: "3.6"
services:
    apps:
        image: apps
        build: ./docker/
        ports:
            - 1481:81       # angular dist  http://localhost:1481/ 
            - 1482:82       # angular dev   http://localhost:1482/ 
            - 1484:84       # polymer dist  http://localhost:1484/
            - 1488:88       # polymer dev   http://localhost:1488/
        volumes:
            - ./app:/usr/share/app
            - ./dist:/usr/share/nginx/html
