version: "3.6"
services:
    apps:
        container_name: dev.app
        image: dev/app
        build: 

            context: ./docker/app
            args:
                - email=gmail@metlinskyi.com
                - name=Roman Metlinskyi
        ports:
            - 1481:81 # angular dev   http://localhost:1481/ 
            - 1482:82 # reactjs dev   http://localhost:1482/   
            - 1484:84 # vurejs  dev   http://localhost:1484/   
            - 1485:85 # emberjs dev   http://localhost:1485/  
            - 1488:88 # polymer dev   http://localhost:1488/
        volumes:
            - ./app:/usr/share/app
        env_file:
            - ./docker/variables.env