version: "3.6"
services:
    apps:
        image: apps
        build: ./docker/
        ports:
            - 1480:80       # angular dist http://localhost:1480/ 
            - 1488:88       # polymer dist http://localhost:1488/
            - 4000:4200     # angular dev http://localhost:4000/ 
            - 3000:3000     # polymer dev http://localhost:3000/
        volumes:
            - ./app:/usr/share/app
            - ./dist:/usr/share/nginx/html

         
# ng serve --open
# polymer serve --port 3000
