FROM    nginx:alpine

LABEL   maintainer="Roman Metlinskyi" \
        email="gmail@metlinskyi.com" \
        version="1.0"

        # Install certbot
RUN     apk add --no-cache certbot

        # Copy renew cron script
COPY    server/renew /etc/periodic/daily/renew
RUN     chmod +x /etc/periodic/daily/renew
RUN     mkdir /var/lib/certbot

        # Copy nginx configuration files   
COPY    server/config/default.conf     /etc/nginx/conf.d/default.conf     
COPY    server/config/apps/            /etc/nginx/apps/
COPY    server/config/include/         /etc/nginx/

        # Copy entrypoint
COPY    server/entrypoint /entrypoint
RUN     chmod +x /entrypoint

        # Expose ports
EXPOSE  80 443

ENTRYPOINT [ "/entrypoint" ]

