server {

    server_name ~^(www\.)?metlinskyi.com$;

    listen 80;
    listen [::]:80;
    
    include certbot.conf;

    location / {
        return 301 https://metlinskyi.com$request_uri;
    }
}

server {    

    server_name ~^www\.metlinskyi.com$;

    listen 443 ssl;
    listen [::]:443 ssl;

    include ssl.conf;
    include apps/*.conf;
    
    return 301 https://metlinskyi.com$request_uri;
}

server {

    server_name localhost ~^(?!www\.)metlinskyi.com$;

    listen 443 ssl;
    listen [::]:443 ssl;

    root /var/www;

    include system.conf;
    include static.conf;
    include robots.conf;
    include certbot.conf;  
    include ssl.conf;  

    include apps/*.conf;
}