# gRPC proxy configuration
location / {
    grpc_pass grpc://api:8082;
    grpc_set_header Content-Type "application/grpc";
    grpc_set_header Proxy-Connection "";
    grpc_set_header x-forwarded-proto http;
    grpc_set_header grpc-accept-encoding identity;
}