# gRPC SSL configuration
grpc_ssl_certificate       /etc/nginx/ssl/certificate.pem;
grpc_ssl_certificate_key   /etc/nginx/ssl/certificate_key.pem;
grpc_ssl_certificate_cache max=1000 inactive=20s valid=1m;