# Development server configuration
server {

    server_name     localhost;

    listen          [::]:443 ssl;
    listen          443 ssl;
    http2           on;

    root            /var/www;

    include         api.conf;
    include         default.conf;
    include         public.conf;
    include         robots.conf;
    include         ssl/ssl.conf;
    include         static.conf;
    include         system.conf;
}
# gRPC server configuration
server {

    server_name     localhost;
    default_type    application/grpc;

    listen          [::]:8080 ssl;
    listen          8080 ssl;
    http2           on;   

    include         grpc.conf;
    include         ssl/ssl.conf;
}   
