#!/bin/sh

certbot certonly -n -d \
  metlinskyi.com,www.metlinskyi.com \
  --standalone --preferred-challenges http --email admin@metlinskyi.com --agree-tos --expand

# Kick off cron
/usr/sbin/crond -f -d 8 &

# Start nginx
/usr/sbin/nginx -g "daemon off;"