name: API

on:
  push:
    branches: [ "_" ]
    paths: ['data.yaml']

  workflow_dispatch:

jobs:

  API:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build API Docker image
        run: | 
            docker build --pull --rm -f "dockerfile.api" -t metlinskyi/com:api "."
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
            docker push metlinskyi/com:api
      - name: Deploy to server
        run: |
          ssh $GIT_HUB_USERNAME@metlinskyi.com -t \
          "
            docker container stop api || true && \
            docker container rm api || true && \
            docker pull metlinskyi/com:api && \
            docker run -d --restart always \
                  --name api \
                  --network=metlinskyi \
                  -h api \
                  metlinskyi/com:api
          "

  DATA:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Data Docker image
        run: | 
            docker build --pull --rm -f "dockerfile.data" -t metlinskyi/com:data "."
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
            docker push metlinskyi/com:data
      - name: Deploy to server
        run: |
          ssh $GIT_HUB_USERNAME@metlinskyi.com -t \ 
          "
            docker container stop api || true && \
            docker pull metlinskyi/com:data && \
            docker run -d \
                  --name data \
                  --network=metlinskyi \
                  metlinskyi/com:data \
            docker container start api
          "

  SERVER:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Server Docker image
        run: | 
            docker build --pull --rm -f "dockerfile.server" -t metlinskyi/com:server "."
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
            docker push metlinskyi/com:server
      - name: Deploy to server
        run: |
          ssh $GIT_HUB_USERNAME@metlinskyi.com -t \ 
          "
            docker container stop server || true && \
            docker container rm server || true && \
            docker pull metlinskyi/com:server && \
            docker run -d --restart always \
                    --name server \
                    --network=metlinskyi \
                    -h server \
                    -p 80:80 \
                    -p 443:443 \
                    -p 8080:8080 \
                    -v www:/var/www:ro \
                    -v letsencrypt:/etc/letsencrypt/live/metlinskyi.com:rw \
                    metlinskyi/com:server
          "

  WWW:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build UI Docker image
        run: | 
            docker build --pull --rm -f "dockerfile.www" -t metlinskyi/com:www "."
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
            docker push metlinskyi/com:www
      - name: Deploy to server
        run: |
          ssh $GIT_HUB_USERNAME@metlinskyi.com -t \ 
          "
            docker container stop www || true && \
            docker container rm www || true && \
            docker pull metlinskyi/com:www && \
            docker run -d \
                  --name www \
                  --network=metlinskyi \
                  metlinskyi/com:www
          "